language: nodejs
node_js:
  - 0.7
notifications:
  email: false
before_script:
  - node --version
  - sudo npm install -g grunt
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - grunt
  - /usr/local/bin/phantomjs ./tests/qunit/phantomjs.js 'http://localhost:8080/tests/qunit/jquery.animate-enhanced.js.test.html'
  - /usr/local/bin/phantomjs ./tests/qunit/phantomjs.js 'http://localhost:8080/tests/qunit/jquery.animate-enhanced.js.test.html?jquery=1.7'
  - /usr/local/bin/phantomjs ./tests/qunit/phantomjs.js 'http://localhost:8080/tests/qunit/jquery.animate-enhanced.js.test.html?jquery=1.6'
  - /usr/local/bin/phantomjs ./tests/qunit/phantomjs.js 'http://localhost:8080/tests/qunit/jquery.animate-enhanced.js.test.html?jquery=1.5'
  - /usr/local/bin/phantomjs ./tests/qunit/phantomjs.js 'http://localhost:8080/tests/qunit/jquery.animate-enhanced.js.test.html?jquery=1.4'
        
