language: nodejs
node_js:
  - 0.7
notifications:
  email: false
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - node --version
  - npm install connect
  - node ./tests/qunit/server.js /../../ 8080 &
  - sleep 3
script: 
  - /usr/local/bin/phantomjs ./tests/qunit/phantomjs.js 'http://localhost:8080/tests/qunit/jquery.animate-enhanced.js.test.html'
