language: nodejs
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "/usr/local/bin/phantomjs ./tests/qunit/phantomjs.js ./tests/qunit/jquery.animate-enhanced.js.test.html"